[package]
name = "wakemeup"
version = "0.1.0"
authors = ["emmachase <its.emma.chase@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-pigpio = "0.2"
ws = { version = "0.9", features = ["ssl"] }